services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend-app
      dockerfile: ./Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8081/api
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always

  backend:
    container_name: backend
    build:
      context: ./ElectronicStore
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    restart: always

  db:
    container_name: db
    image: "mysql"
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=electronic_store
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
